### ISSUE TITLE
Improve readability of test files

### ISSUE THREAD

**Issue by ltrojanowski** [oovm/neo-intellij#2]
Hi. First of all I absolutely love this theme. Thanks for creating it. I have just one issue with it. The names of the test files are not well visible. This is particularly true if there is a new file and git integration is turned on. Then the file name is green on a green background.
This is how it currently looks like:
![Screenshot 2022-01-26 at 10 49 31](https://user-images.githubusercontent.com/3951626/151142330-30ed7819-beed-4e12-b2f5-1215bc5d4f15.png)
I think a more subtle pastel green could improve the contrast a lot. I was thinking something like this (color: #8da477)
![sample-change](https://user-images.githubusercontent.com/3951626/151142740-ee4625d4-bb5c-4dde-8ad5-09f020766e4a.png)

This was changed in gimp so there are some artefacts around the letters but I'm sure you get the point.
I think the value which controls this is under UI.FileColor.Green line 293 in "Neo Light.json".

**Comment by oovm** [comment]
The night theme is like this too, I'm not sure if it's going to be changed together.

**Comment by oovm** [comment]
I personally feel that the gray words are not prominent enough, the green background can be lighter, but the saturation should be higher

**Comment by ltrojanowski** [comment]
Did you have time to find a shade of green you like? I'm wondering if you will publish this in 0.2.1 of your theme?

**Comment by oovm** [comment]
The new version of UI (ExpUI 2024) has changes in color matching

To accommodate this change, `#C4EF99` will be used starting from 0.4.1.


![image](https://github.com/oovm/neo-intellij/assets/17541209/cc94fa12-7c28-4393-834f-1a68cce8b302)
