### ISSUE TITLE
Background color should be changed for completion popup in light theme

### ISSUE THREAD

**Issue by metacosm** [oovm/neo-intellij#5]
As it is, it's impossible to tell which item is selected in the completion popup because the background color matches the foreground one.

Thank you for a very clean theme, by the way! 😊

**Comment by oovm** [comment]
Confirm that the problem exists

![image](https://user-images.githubusercontent.com/17541209/156730691-af991e6f-8581-43cb-9329-7e98187b1d57.png)

![image](https://user-images.githubusercontent.com/17541209/156730585-922824d3-237f-404d-9e70-e3e09ea9185b.png)

**Comment by metacosm** [comment]
I just changed the background color for completion as a quick fix: 

<img width="1066" alt="Screenshot 2022-03-04 at 10 30 50" src="https://user-images.githubusercontent.com/120057/156737374-cae1afe6-a027-462f-8a01-6aef0dbc000a.png">

**Comment by MrVideo** [comment]
I have found that F2F2F2 looks good as well, as it is the sidebar colour. Leaving this here for anyone with the same issue.

**Comment by oovm** [comment]
This should be fixed in newer versions, and custom background colors should not be affected
