### ISSUE TITLE
Wrong line height for Member Selection in Extract Delegate 

### ISSUE THREAD

**Issue by fishermans** [oovm/neo-intellij#8]
IntelliJ 2023.2.2 Ultimate:

Cannot read members in Refactor / Extract Delegate dialog:

<img width="823" alt="image" src="https://github.com/oovm/neo-intellij/assets/4817889/33a0bc09-5713-476f-8a5d-4a93cd4e4243">

**Comment by oovm** [comment]
Fixed by

https://github.com/oovm/neo-intellij/blob/d14903cd310fbfd99f21dd8193e94392491c252d/src/main/resources/themes/Neo%20Night.json#L762

New version under reviewing

**Comment by fishermans** [comment]
Thanks. I already used "cellNoFocusBorder": "10,5,10,5".

Setting "cellNoFocusBorder": "5,5,5,5" would fix it for me:

<img width="642" alt="image" src="https://github.com/oovm/neo-intellij/assets/4817889/e012394c-24da-4f3c-b467-e37923ec589d">

<img width="755" alt="image" src="https://github.com/oovm/neo-intellij/assets/4817889/ec747bd3-3740-42a8-a93c-03eae4aaa46c">

**Comment by fishermans** [comment]
Thanks! Version 0.3.2 looks good to me!
